# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop', '0003_auto_20170403_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
